#!/usr/bin/env bash
# gotchas-index.sh — regenerate docs/gotchas/INDEX.md from the YAML
# front-matter of every docs/gotchas/GOTCHA-*.md file.
#
# Idempotent. Safe to run from a pre-commit hook or from CI.
# Exits 0 on success, 1 on parse error (and reports the offending file).
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
DIR="$ROOT/docs/gotchas"
INDEX="$DIR/INDEX.md"

[[ -d "$DIR" ]] || { echo "no $DIR — nothing to index" >&2; exit 0; }

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

shopt -s nullglob
errors=0
for f in "$DIR"/GOTCHA-*.md; do
    base="$(basename "$f")"
    [[ "$base" == "_TEMPLATE.md" ]] && continue

    fm="$(awk '
        /^---[[:space:]]*$/ { c++; if (c==2) exit; next }
        c==1 { print }
    ' "$f")"

    if [[ -z "$fm" ]]; then
        echo "error: $f has no YAML front-matter" >&2
        errors=$((errors+1))
        continue
    fi

    get() {
        echo "$fm" | awk -v k="$1" '
            $0 ~ "^"k":" {
                sub("^"k":[[:space:]]*", "")
                gsub(/^"|"$/, "")
                print
                exit
            }'
    }

    id="$(get id)"
    sev="$(get severity)"
    status="$(get status)"
    discovered="$(get discovered)"
    title="$(awk '/^# /{ sub(/^# /,""); print; exit }' "$f")"
    scope="$(echo "$fm" | awk '
        /^scope:/ { in_s=1; next }
        in_s && /^[[:space:]]*-[[:space:]]/ {
            sub(/^[[:space:]]*-[[:space:]]*/, ""); rows[++n]=$0; next
        }
        in_s && /^[^[:space:]]/ { in_s=0 }
        END { for (i=1;i<=n;i++) printf "%s%s", rows[i], (i<n?", ":"") }
    ')"

    printf '| [%s](%s) | %s | %s | %s | %s | %s |\n' \
        "$id" "$base" "${title:-?}" "${sev:-?}" "${status:-?}" \
        "${scope:-?}" "${discovered:-?}" >> "$TMP"
done

if [[ "$errors" -gt 0 ]]; then
    echo "gotchas-index.sh: $errors file(s) had errors — index NOT updated" >&2
    exit 1
fi

{
    cat <<'HEADER'
# Gotchas index

> **Auto-generated by `scripts/gotchas-index.sh`. Do not edit by hand.**
>
> Each row is a gotcha discovered during prior work that costs the next
> agent tokens to rediscover. Read this file at Step 0 of every skill.
> If a row's `scope` overlaps your epic, open the linked document.

| ID | Title | Severity | Status | Scope | Discovered |
|----|-------|----------|--------|-------|-----------|
HEADER
    if [[ -s "$TMP" ]]; then
        sort -V "$TMP"
    else
        echo "| _none yet_ | | | | | |"
    fi
    cat <<'FOOTER'

<!-- generated:start -->
<!-- generated:end -->
FOOTER
} > "$INDEX"

echo "wrote $INDEX ($(wc -l <"$TMP") entries)"
